dataset:
  nanopore_name: GRAPHENE
  molecule_name: ALA
  num_angle_feats: 3
  num_dist_feats: 100
  num_elec_feats: 200
  min_photo_energy: 0
  max_photo_energy: 2

random_seed: 1234

preprocess:
  n_components: 10
  log_base: 10
  log_eps: 1.0
  test_size: 0.1
  set_yscale_log: false
  test_size: 0.1

shap:
  shap_analysis: false
  num_angle_feats_shap: 3
  num_dist_feats_shap: 20
  num_elec_feats_shap: 20

training:
  device: cpu
  num_epochs: 1000
  lr_rate: 0.001
  dropout: 0.2
  l1_lambda: null
  weight_decay: null
  hidden_dims: [128, 128, 128]
  final_activation: null
  print_every: 10


tuning:
  hyper_tuning: false
  param_grid:
    hidden_dims:
      - [64, 64]
      - [128, 128]
      - [64, 64, 64]
      - [128, 128, 128]
    dropout: [0.1, 0.2, 0.3, 0.5]
    lr_rate: [0.01, 0.001, 0.0001]
    weight_decay: [null, 0.000001, 0.00001]
    num_epochs: [100, 200, 400, 600, 800]
  print_every: 100

plotting:
  plot_pca_cumulative_variance: true
  plot_train_val_loss: false
  plot_shap_analysis_bar: false
  plot_model_scores: true
  plot_absorption_prediction: true
  plot_absorption_prediction_nrows: 4
  plot_absorption_prediction_ncols: 4

paths:
  dataset_dir: datasets
  # raw_dataset_dir: datasets/raw
  # clean_dataset_dir: datasets/clean
  figure_save_dir: results/figures
  model_save_dir: results/models
